version: "3.5"

services:
    postgres:
        image: postgres:13-alpine
        container_name: flask-postgres
        ports:
            - ${POSTGRES_PORT}:5432
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASS}
            POSTGRES_USER: postgres
            TZ: Asia/Taipei
        volumes:
            - ./db/postgres:/var/lib/postgresql/data
        networks:
            - flask_network
        restart: always

networks:
    flask_network:
        external: true
        name: flask_network
        driver: bridge
